### PR TITLE
Modern Landing Page is created.

### LINKED ISSUE #14: Modern landing page
Hey @samarthhapse,

I'd love to contribute a **modern and interactive landing page** from scratch. It'll include:

Modern design elements like gradients and animations.
Interactive components such as sliders and smooth scrolling.
Engaging content with testimonials and client logos.
Fully responsive and accessible design.
Integration with existing branding guidelines.

Excited to get started!

my recent works attached here, 
Screenshot 2024-03-16 202700

### PR DESCRIPTION
**Pull request by Abhishek-465**
## Modern Landing Page 
Fixes #14 

I have made the landing page by taking the reference as you have provided.Additionally i have added on scroll animations, hover effects and color changing backgrounds as per requirement. You can further change the content and the images.
## Video:

https://github.com/samarthhapse/sarthi/assets/127030695/7f80e4a3-17d9-4c3a-8974-89bb91e8f2c3

Contributing under GSSOC 24.

### CODE REVIEW

**Comment by samarthhapse** [comment]
hello @Abhishek-465 your PR have some conflicts , pls solve and make video with recording of sign-up and sign-in page

**Comment by samarthhapse** [comment]
@Abhishek-465  once just go through App.jsx , there are some conflicts.

**Comment by Abhishek-465** [comment]
@samarthhapse  I have resolved the conflict. I have not made any changes on the sign up sign in pages as it was not a part of this issue.

https://github.com/samarthhapse/sarthi/assets/127030695/03aaff70-1cf0-4775-a937-c6b60b7358bc

**Comment by samarthhapse** [comment]
nice work ! @Abhishek-465 . Added label of level 3

**Comment by Abhishek-465** [comment]
Thank you @samarthhapse

**Comment by samarthhapse** [comment]
hello @Abhishek-465 , I found one mistake in you PR, hence reversed it. You are directing to the landing page onclick of login button,  instead it should go on the below page . Pls make that change.

**Comment by samarthhapse** [comment]
Screenshot 2024-06-05 124259

direct on this page , after clicking on login button

**Comment by Abhishek-465** [comment]
Done and committed in the layout branch.

https://github.com/samarthhapse/sarthi/assets/127030695/12ccd838-9bf1-4878-afa8-69273df7ccf3

**Comment by Abhishek-465** [comment]
@samarthhapse but to reflect this small change i need to make another PR. This reverting is not working. Should i make another PR?

**Comment by samarthhapse** [comment]
Yes, pls make PR on temp

**Comment by samarthhapse** [comment]
Yes, pls make PR on temp

**Comment by Abhishek-465** [comment]
Done

**Pull request merged**
