### PR TITLE
Solved the #191 issue

### PR DESCRIPTION
**Pull request by ROKUMATE**
Solved the issue #191 

For Correctly accessing the google auth, 

u have to create a google API project and all the required changes and all for getting the Google Gpis `Client Secret` and `Client id`

then copy them and  create a profile on the appwrite page and there create a `project` > `Auth` > `setting` > `Oauth2Provider` > select "Google" 
and enter the copied client id and the client secret and copy the site URL and the client id and paste in the frontend .env file 
```
VITE_APPWRITE_ENDPOINT=<ENTER_REQUIRED_DETAILS>
VITE_APPWRITE_PROJECT=<ENTER_REQUIRED_DETAILS>
```
in this format

### CODE REVIEW

**Comment by ROKUMATE** [comment]
@samarthhapse Sir is there any issue in this u haven't merged it yet ?

**Comment by ROKUMATE** [comment]
I have solved all the conflicts

**Comment by samarthhapse** [comment]
@ROKUMATE well done ! merged it

**Comment by jelly-afk** [comment]
Screenshot from 2024-07-05 10-55-57
Screenshot from 2024-07-05 10-56-39
@samarthhapse @ROKUMATE

**Comment by samarthhapse** [comment]
@jelly-afk , pls fork code from temp-af branch and add your code there. You will not get errors there.Also raise PR on temp-af branch only

**Comment by samarthhapse** [comment]
@jelly-afk created temp-af after merging your chat code only

**Comment by samarthhapse** [comment]
@jelly-afk is (temp-af) working fine ?

**Comment by jelly-afk** [comment]
> @jelly-afk is (temp-af) working fine ?

Yes

**Pull request merged**
