### PR TITLE
Added  Razorpay payment integration

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #216 

https://github.com/user-attachments/assets/cdb14e8f-fa8c-4a6a-bab0-9a074b147a30

### CODE REVIEW

**Comment by pani2004** [comment]
@samarthhapse Pls review the PR!!!

**Comment by samarthhapse** [comment]
@pani2004 , great work. But it was expected to add that button on below page. (the detailed page which you get when you click on this expert)

Screenshot 2024-07-19 224028

**Comment by samarthhapse** [comment]
@pani2004 , I have opened #223 for this small issue. I will assign it to you. Just complete it and raise PR. It is level issue, It will help you more to get up on leaderboard

**Comment by samarthhapse** [comment]
@pani2004 here are last two weeks of GSSoC'24 program. Comment below if you are available for some immediate issues.

**Comment by pani2004** [comment]
@samarthhapse yes I can work

**Comment by samarthhapse** [comment]
fine ! @pani2004 raise PR for #223 for now. After this I will assign you a new issue

**Pull request merged**
