### PR TITLE
otp-verification added

### PR DESCRIPTION
**Pull request by ayann07**
#67 is now completed.
otp verification along with frontend and backend done for both student and expert signup.

https://github.com/samarthhapse/sarthi/assets/126085856/24fa6366-022e-4456-8625-7de0d0b29763

I have done this under gssoc'24.

### CODE REVIEW

**Comment by samarthhapse** [comment]
Great ! @ayann07.

**Comment by ayann07** [comment]
Could be nice if you could add level 3 label to it, this pr required a lot of effort :)

**Comment by samarthhapse** [comment]
okay

**Comment by samarthhapse** [comment]
you can start working on #68 now. Comment the expected date of submission.

**Pull request merged**
