### PR TITLE
Whole app dark mode

### PR DESCRIPTION
**Pull request by VaibhavYT**
Now whole has dark and light mode.

This PR solve #130 issue.

### CODE REVIEW

**Comment by samarthhapse** [comment]
@VaibhavYT there are some conflicts. Pls go through once.

**Comment by VaibhavYT** [comment]
Please merge the code.
please add gssoc level it will help me.😁✅👨‍💻

**Comment by samarthhapse** [comment]
added level 3 , okay ?

**Comment by samarthhapse** [comment]
just keep eye on new issues. I will assign

**Comment by samarthhapse** [comment]
Hello @VaibhavYT , you did nice work. But one thing you missed , I said we have to make dark mode default. In website light mode id default

**Comment by samarthhapse** [comment]
btw , I have created #164 to solve this thing

**Pull request merged**
