### PR TITLE
Add/expert home

### LINKED ISSUE #90: expert profile page ( only UI development of => profile picture , details , chat button , payment button , rating feature )
when expert signs up his data gets stored in DB and further when he log in , you should be able to get that data from backend and display expert's profile page

### PR DESCRIPTION
**Pull request by jelly-afk**
fixes #90 added home expertHomePage where he can edit his details

### CODE REVIEW

**Comment by samarthhapse** [comment]
Well done ! @jelly-afk , hope you will complete step 2 mentioned in #90 by tommorow EOD

**Comment by jelly-afk** [comment]
@samarthhapse step 2 is just creating a expert profile component which is just design

**Comment by samarthhapse** [comment]
@jelly-afk yeah ! make it asap. Wo just need to make an api call to get expert's updated data

**Comment by samarthhapse** [comment]
okay @jelly-afk , I will tell assign it to someone

**Comment by samarthhapse** [comment]
@jelly-afk why contributors are getting error while sending opt. Was there any change in otp functionality

Screenshot 2024-06-17 221528

**Comment by samarthhapse** [comment]
@jelly-afk , my suggestion is , you must complete step 2 , don't focus on UI make it as you want , just fetch and show data to student. It is creating confusions between various contributors

**Comment by samarthhapse** [comment]
@jelly-afk , I have created new issue #177 , I will assign it to you

**Comment by samarthhapse** [comment]
@jelly-afk I have checked PRs , otp functionality was workiing properly before merging #161. In PR #161 some changes were made with nodemailer fuctionality and then otp functionality creashed. Pls do go through once asap

**Comment by samarthhapse** [comment]
@jelly-afk very basic and simplest UI is expected from you. Just comment before you start, don't start directly

**Comment by jelly-afk** [comment]
@samarthhapse ok i will do it

**Comment by samarthhapse** [comment]
yeah !

**Pull request merged**
