### PR TITLE
Chat functionality backend

### PR DESCRIPTION
**Pull request by mehtakevan**
Implemented All the apis necessary for chat functionality.

Some screenshot of test:

1)Access Chat Api
accessChat

2)FetchChat
fetchChats

3)Send Message
sendmessage

4)FetchAllMessages
allmessages

Also I have implemented a group chat functionality. Where a student or an expert can create groups.

### CODE REVIEW

**Comment by mehtakevan** [comment]
@samarthhapse Can you please make me as assignee...
And I think it should be labeled some higher level than level 1, Although at last it's your decision.

**Comment by samarthhapse** [comment]
@mehtakevan , I tried to connect with 2-3 contributors . But they are getting little bit confused

**Comment by samarthhapse** [comment]
@mehtakevan , are you available now ?

**Comment by samarthhapse** [comment]
@mehtakevan , as you built backend by own , you might be well familiar with frontend connection part

**Comment by samarthhapse** [comment]
@mehtakevan , very basic and simple frontend is expected from you side

**Pull request merged**
