### PR TITLE
add view chats

### PR DESCRIPTION
**Pull request by jelly-afk**
user can see all their chats

### CODE REVIEW

**Comment by jelly-afk** [comment]
minimum design

**Comment by samarthhapse** [comment]
@jelly-afk , I think you have not understood properly. You did not needed to add chat icon on home page

**Comment by jelly-afk** [comment]
> @jelly-afk , I think you have not understood properly. You did not needed to add chat icon on home page

It's so that they can access their previous chats

**Comment by samarthhapse** [comment]
@jelly-afk , see this app will be used by student and expert both. I wanted them both to chat with each other only. Now let any student sends a message to expert. Now as expert sign in where he is getting all the messages of such students

**Comment by samarthhapse** [comment]
@jelly-afk , as of current code any student can see chats of any others , without any login and signup.

**Comment by jelly-afk** [comment]
> @jelly-afk , as of current code any student can see chats of any others , without any login and signup.

No, they need to login to see the chat icon

**Comment by samarthhapse** [comment]
I tried but they do not need to login for it. If you pls remove that chat icon from navbar and add that chat icon on expert profile page. I think the issue will get resolved. Pls try it once

**Comment by samarthhapse** [comment]
@jelly-afk additionally you can also try to add logout buttons for them

**Comment by samarthhapse** [comment]
Screenshot 2024-07-06 111102

if you remove chat icon from navbar and add it on this page . I think issue will get resolved

**Comment by samarthhapse** [comment]
@jelly-afk pls try it out once !

**Comment by jelly-afk** [comment]
> @jelly-afk  I tried but they do not need to login for it. If you pls remove that chat icon from navbar and add that chat icon on expert profile page. I think the issue will get resolved. Pls try it once
> 
> 

You're already logged in because your info is stored in local storage

**Comment by samarthhapse** [comment]
> @jelly-afk I tried but they do not need to login for it. If you pls remove that chat icon from navbar and add that chat icon on expert profile page. I think the issue will get resolved. Pls try it once

right, but can you pls try his thing once to make it less complicated

**Comment by samarthhapse** [comment]
@jelly-afk , I can add some more points for this try

**Comment by jelly-afk** [comment]
> Screenshot 2024-07-06 111102
> 
> if you remove chat icon from navbar and add it on this page . I think issue will get resolved

only on expert Profile or student profile too?

**Comment by jelly-afk** [comment]
> @jelly-afk , I can add some more points for this try

no need for this one

**Comment by samarthhapse** [comment]
@jelly-afk , added +30 points for the PR

**Comment by samarthhapse** [comment]
@jelly-afk , if you are free and can work on #172 ( pls do red my first comment for problem description) , you can comment there. I assigned it to someone else but he left it in mid. It is 40 points issue for VSSoC'24. But if you are willing to work let first discuss more about it on #172 only

**Pull request merged**
