### PR TITLE
Implement email verification for new expert signups

### PR DESCRIPTION
**Pull request by Shreyasaraf01**
- Updated index.js to use environment variables for email configuration
- Added /signup and /authorize endpoints to handle signup requests and authorizations
- Integrated nodemailer for sending signup notifications to the website owner

Fixes: #205

### CODE REVIEW

**Comment by samarthhapse** [comment]
@Shreyasaraf01 , it's okay , you are adding your part of code in index.js But why you are removing all the api routes from it. Please keep current index.js as it is and just add your part of code.

**Comment by Shreyasaraf01** [comment]
Ok

**Comment by samarthhapse** [comment]
When any one try to sign up as expert => manojhapse20@gmail.com,  this mail should get a confirmation mail . If mail holder of manojhapse20@gmail.com confirms from his side then only expert's account should be created

**Comment by samarthhapse** [comment]
When any one try to sign up as expert => manojhapse20@gmail.com,  this mail holder should get a confirmation e-mail . If mail holder of manojhapse20@gmail.com confirms from his side then only expert's account should be created

**Comment by samarthhapse** [comment]
When any one try to sign up as expert. manojhapse20@gmail.com <= this mail holder should get a confirmation e-mail . If mail holder of manojhapse20@gmail.com confirms from his side then only expert's account should be created

**Comment by samarthhapse** [comment]
@Shreyasaraf01 , I tried out to add your code and run app. But it is giving some errors. Is it running on your side

**Comment by samarthhapse** [comment]
@Shreyasaraf01 , have any solution for above problem

**Comment by Shreyasaraf01** [comment]
> @Shreyasaraf01 , have any solution for above problem

Hi @samarthhapse ,

I hope this message finds you well. I wanted to inform you that, due to other commitments, I won't be able to continue contributing to the project at this time. I have greatly appreciated the opportunity and have learned a lot through this experience.
Thank you for your understanding.

Best regards,
Shreya Saraf

**Comment by samarthhapse** [comment]
Okay @Shreyasaraf01

**Pull request closed without merging**
