### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ROKUMATE**
Solved the issue #195

### CODE REVIEW

**Comment by samarthhapse** [comment]
@ROKUMATE well done !

**Comment by samarthhapse** [comment]
@ROKUMATE have you ever worked on building a chat app in MERN stack ?

**Comment by ROKUMATE** [comment]
I havent but yestarday u told to handel that issue so was going through documents 
Regarding Websockets 
By today i will be having good enough info to start buidling up that chat integration.

**Comment by ROKUMATE** [comment]
#@samarthhapse in that chat integration what u exactly want just bckend or frntend or both ?

**Comment by samarthhapse** [comment]
@ROKUMATE , backend is already added you need to build new frontend and connect it with backend

**Comment by samarthhapse** [comment]
@ROKUMATE properly try it out first

**Comment by samarthhapse** [comment]
@ROKUMATE I have already assigned it to someone , but if he fails. I will assign it to you , If you will be able to create

**Comment by ROKUMATE** [comment]
@samarthhapse okk sir no issues 👍

**Comment by samarthhapse** [comment]
Pls call Samarth

**Comment by samarthhapse** [comment]
Hello , @ROKUMATE , for chat feature . you have 2 options

1.backend is added , build frontend and connect with frontend
2.build complete frontend and backend of you own.

I have 2 different codebases for two options

**Comment by samarthhapse** [comment]
@ROKUMATE , main part is =>

after sign in of student when he selects expert of his choice , he will be able to see detailed profile of the expert. You need to add "chat" button here and on click of this button expert and student should be able to chat within both of them only.

**Comment by ROKUMATE** [comment]
I will mostly go with 2. but will let u know by tmrr morning or afternoon which one i will be more confortable with

**Comment by ROKUMATE** [comment]
> @ROKUMATE , main part is =>
> 
> 
> 
> after sign in of student when he selects expert of his choice , he will be able to see detailed profile of the expert. You need to add "chat" button here and on click of this button expert and student should be able to chat within both of them only.

Understood 👍

**Comment by samarthhapse** [comment]
> I will mostly go with 2. but will let u know by tmrr morning or afternoon which one i will be more confortable with

well ! just inform me tomorrow

**Comment by samarthhapse** [comment]
@ROKUMATE have you gone through it.

**Comment by samarthhapse** [comment]
@ROKUMATE pls update

**Comment by samarthhapse** [comment]
okay @ROKUMATE  no problem, only the proper working chat feature where the individual student and expert can chat with each other is expected

**Comment by samarthhapse** [comment]
Screenshot 2024-06-23 175219

when student sign in and select expert of his choice , he get this page , you have to add here a chat button for that student to chat with this expert.

**Comment by samarthhapse** [comment]
@ROKUMATE pls comment with the expected date of submission. 

IMP. NOTE => fork the code from temp3 branch only

**Comment by ROKUMATE** [comment]
Atmost by this sat i will try to complete👍

**Comment by samarthhapse** [comment]
Saturday is so far. But okay , just be sure to raise PR by Sunday morning

**Comment by samarthhapse** [comment]
@ROKUMATE , hope it's going good

**Comment by samarthhapse** [comment]
@ROKUMATE , BEFORE raising pr just comment this => ( ready to raise PR ) here only

**Comment by ROKUMATE** [comment]
Sir u have already merged the chat functionality ig ... right ?

**Comment by samarthhapse** [comment]
@ROKUMATE that one is on temp branch. You have forked and working on temp3 branch right ?

**Comment by samarthhapse** [comment]
@ROKUMATE as you are working on temp3 and are going to raise PR on temp3 only. So do not worry ! I will surely merge you PR

**Comment by samarthhapse** [comment]
@ROKUMATE keep going ! and raise asap

**Comment by samarthhapse** [comment]
@ROKUMATE pls ask doubts, if any ?

**Comment by ROKUMATE** [comment]
Okkkok👍

**Comment by ROKUMATE** [comment]
Sir i have created fork with the temp branch only and edited that soo let it be i will work on other issue if that is over 😅

**Comment by samarthhapse** [comment]
okay. I will comment here only to contact you

**Comment by samarthhapse** [comment]
> Sir i have checked i created fork with the temp branch only and edited that soo let it be i will work on other issue if that is over 😅

I have mentioned to fork it from temp3 before you start. But let it go

**Comment by samarthhapse** [comment]
@ROKUMATE I will contact with you here only

**Comment by samarthhapse** [comment]
Hello @ROKUMATE , available to work on #215 OR #216

**Comment by ROKUMATE** [comment]
Sir i am travelling roght now back to hostel will continue working frm
Monday onwards or tuesday kost probably 👍🏻

I will look on to that issue, if i am able to do, i will inform here itself 👍🏻

**Comment by samarthhapse** [comment]
okay @ROKUMATE , just comment there once you are available

**Pull request merged**
