### PR TITLE
authentication-frontend done

### PR DESCRIPTION
**Pull request by ayann07**
The UI is modified now.
issue number #70 is now complete.

https://github.com/samarthhapse/sarthi/assets/126085856/296487e7-890d-4811-a95d-f14dd1a11630

I have done this under gssoc'24.

### CODE REVIEW

**Comment by samarthhapse** [comment]
your pr might be 1 commit behind ayaan as I have merged on more pr for the preloader 2 days ago

**Comment by ayann07** [comment]
So what should I do now?

**Comment by samarthhapse** [comment]
nothing

**Comment by ayann07** [comment]
Please add a label to it of gssoc and level aswell

**Comment by samarthhapse** [comment]
@ayann07 I thiing I have assigned #68 to you. Is it completed.

**Comment by samarthhapse** [comment]
I have added labels

**Comment by ayann07** [comment]
I was working on another issue that is otp verification while signup, I have completed that both backend and frontend of it,now I will work on #68 issue.

**Comment by ayann07** [comment]
So issue #67 is also now completed, in 30 mins I'll create a pull request

**Comment by samarthhapse** [comment]
okay but make sure that PR will maintain the changes of this PR

**Pull request merged**
