### PR TITLE
Added The UI for The main Page

### PR DESCRIPTION
**Pull request by Priyanshu2743**
I have added the UI of the main page 
but due to changes in code which you have merged 

I will add the NavBar and Footer in the another PR

Video of the working UI

https://github.com/samarthhapse/sarthi/assets/124867297/fe86b9ad-a3a9-4b29-aa8e-339ed476c4cb

### CODE REVIEW

**Comment by Priyanshu2743** [comment]
Hii @samarthhapse 

Sorry for delay in processing and merging Pr

### But kindly, pls add the label of level 3 as the issue is of level 3

I will add another features which could not be merged with this pr as After you added codes, there is difficulty in merging all the codes and making them able to merge it

**Comment by samarthhapse** [comment]
no worries @Priyanshu2743 , you must just keep updating about the things ! 
I am adding the label of level 3.

**Comment by Priyanshu2743** [comment]
Yeah!! I will

Thanks A lot

**Comment by Priyanshu2743** [comment]
Kindly assign the issue #87

**Pull request merged**
