### PR TITLE
backend initialized

### PR DESCRIPTION
**Pull request by ayann07**
I have initialized the backend using MVC structure, moreover I have written the backend for student and expert.
The controllers for register, login, change password , get details of all experts/students and get details of a single expert/ student is implemented successfully.
issue no #24 is now completed.
I have worked on this under GSSOC'24.

### CODE REVIEW

**Comment by ayann07** [comment]
Please merge my pull request @samarthhapse

**Comment by samarthhapse** [comment]
@ayann07 I have merged the pull request

**Comment by ayann07** [comment]
@samarthhapse please assign a level to it so that I get good points of gssoc.

**Comment by samarthhapse** [comment]
Great work ! @ayann07 , Actually this issue was already been started earlier on #10 , so I haven't noticed #14. btw, now you can help on other contributors on #10 If they have any issue with this backend codebase

**Comment by ayann07** [comment]
Yeah sure, kindly put a label on it of gssoc and level 3 aswell. IT will give me good points for gssoc leaderboard.

**Comment by samarthhapse** [comment]
okay buddy !

**Comment by ayann07** [comment]
Hey @samarthhapse you have put the label on the issue, put the label on this pull request, as label on this pull request shall only be counted. Thankyou.

**Pull request merged**
