### PR TITLE
Update styles for scrollbars and logo in the app

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #240 

https://github.com/user-attachments/assets/4e99c0c5-c8b4-4ea1-8845-2ed6882594f1

### CODE REVIEW

**Comment by pani2004** [comment]
@samarthhapse review the PR

**Comment by samarthhapse** [comment]
@pani2004 , where is that google translater logo

**Comment by samarthhapse** [comment]
@pani2004 that select language tab was opening and closing onclick of that icon only pls add it near that moon icon

**Comment by samarthhapse** [comment]
@pani2004 , also pls try to reduce this length little bit

InkedInkedAnnotation 2024-08-06 150444_LI

**Comment by pani2004** [comment]
https://github.com/user-attachments/assets/04a3d31f-e04a-4dbe-8cdb-2887a302e088

@samarthhapse made the changes in the recent commit pls check

**Comment by samarthhapse** [comment]
well @pani2004 ! everything is added correctly ! I have added labels on PR as well.

**Pull request merged**
