### PR TITLE
Add/avatar cloudinary

### LINKED ISSUE #158: avatar and cloudinary integration

### PR DESCRIPTION
**Pull request by jelly-afk**
fixes #158 
configured multer and cloudinary 
improved and fixed nodemailer issues
added add avatar functionality for expert

### CODE REVIEW

**Comment by samarthhapse** [comment]
okay , now you might be free to work on #90

**Comment by samarthhapse** [comment]
hello @jelly-afk , started working on chat functionality ?

**Comment by samarthhapse** [comment]
@jelly-afk , pls comment with expected date of submission . Whatever it be.

**Comment by jelly-afk** [comment]
> @jelly-afk , pls comment with expected date of submission . Whatever it be.

Will try to complete in next 2-3 days

**Comment by samarthhapse** [comment]
okay !

**Pull request merged**
