### PR TITLE
added sign in with google option

### PR DESCRIPTION
**Pull request by Krishna100604**
@samarthhapse  merge this

### CODE REVIEW

**Comment by samarthhapse** [comment]
@Krishna100604 added you as assignee and also added labels

**Comment by samarthhapse** [comment]
@Krishna100604 , pls tell to any of the  VSoC manager to add points for you

**Comment by Krishna100604** [comment]
> @Krishna100604 , pls tell to any of the VSoC manager to add points for you

how many points for this

**Comment by Krishna100604** [comment]
> @Krishna100604 , pls tell to any of the VSoC manager to add points for you

why can't you add i give you my email : Shrikrishnaprajapati106@gmail.com

**Comment by samarthhapse** [comment]
@Krishna100604 added 10 points , pls check

**Comment by Krishna100604** [comment]
> @Krishna100604 added 10 points , pls check

ok

**Pull request merged**
