### PR TITLE
Add chat

### LINKED ISSUE #182: basic frontend for chat feature (backend task is completed already)

### PR DESCRIPTION
**Pull request by jelly-afk**
fixes #182 
added backed for chat
added frontend for chat
implemented real time chat feature

### CODE REVIEW

**Comment by jelly-afk** [comment]
@samarthhapse you can give me points on discord registered there with same email

**Comment by samarthhapse** [comment]
@jelly-afk nice ! Added 70 in total points for your total PRs till the date

**Comment by samarthhapse** [comment]
@jelly-afk nice ! Added 70 in total points for your total PRs till the date

jelly

**Comment by jelly-afk** [comment]
thanks

**Comment by samarthhapse** [comment]
@jelly-afk , I checked it but why experts are not recieving messages

**Comment by samarthhapse** [comment]
@jelly-afk is there no feature on expert side to receive and send messages

**Comment by samarthhapse** [comment]
@jelly-afk , can you pls add and raise PR by today

**Comment by jelly-afk** [comment]
> @jelly-afk is there no feature on expert side to receive and send messages

They can both can send and receive messages but there's no message icon for experts to access the chat

**Comment by jelly-afk** [comment]
> @jelly-afk , can you pls add and raise PR by today

Okay

**Comment by samarthhapse** [comment]
> > @jelly-afk , can you pls add and raise PR by today
> 
> Okay

I will add +20 points for today's PR

**Comment by samarthhapse** [comment]
@jelly-afk completed it ?

**Comment by samarthhapse** [comment]
@jelly-afk pls raise PR on temp-af branch only

**Comment by samarthhapse** [comment]
Hello @jelly-afk , have some issue with some part of this PR

**Comment by samarthhapse** [comment]
@jelly-afk , it is small issue, pls comment if you are available for some hours

**Comment by jelly-afk** [comment]
> @jelly-afk , it is small issue, pls comment if you are available for some hours
sure, whats the issue

**Comment by samarthhapse** [comment]
@jelly-afk , first of all thanks a lot ! for the prompt response

**Comment by samarthhapse** [comment]
there is some issue with chat feature
it is working  completely fine. But when multiple students send message to expert he is not getting all the chats to see. Expert can see the chat of only one student
when expert login and click on chat icon => he gets the below page

oneChatOnly

in above imags you can see the student02(and when you click on it you can see chats)
but currently I have messaged the same expert as another student also, but name of that student is not displayed here

**Comment by samarthhapse** [comment]
@jelly-afk ,

IMP. NOTE : pls fork the code from temp-of4 branch only. The updated code is in that branch

**Comment by samarthhapse** [comment]
Hello @jelly-afk , did you look into it

**Comment by samarthhapse** [comment]
> > @jelly-afk , it is small issue, pls comment if you are available for some hours
> 
> sure, whats the issue

@jelly-afk , did you resolved

**Comment by samarthhapse** [comment]
@jelly-afk pls raise PR if done

**Comment by jelly-afk** [comment]
> there is some issue with chat feature it is working completely fine. But when multiple students send message to expert he is not getting all the chats to see. Expert can see the chat of only one student when expert login and click on chat icon => he gets the below page
> oneChatOnly
> 
> in above imags you can see the student02(and when you click on it you can see chats) but currently I have messaged the same expert as another student also, but name of that student is not displayed here

it works fine for me

**Comment by jelly-afk** [comment]
try reloading

**Comment by samarthhapse** [comment]
@jelly-afk , tried it multiple times. Pls try to fork (tenp-of4) branch and have a look of it once

**Comment by samarthhapse** [comment]
@jelly-afk there might be any small thing missing in backend / frontend

**Comment by samarthhapse** [comment]
> > there is some issue with chat feature it is working completely fine. But when multiple students send message to expert he is not getting all the chats to see. Expert can see the chat of only one student when expert login and click on chat icon => he gets the below page
> > oneChatOnly
> > 
> > in above imags you can see the student02(and when you click on it you can see chats) but currently I have messaged the same expert as another student also, but name of that student is not displayed here
> 
> it works fine for me
> 

As an expert are you receiving chats of more than one student ?

**Comment by jelly-afk** [comment]
> > > there is some issue with chat feature it is working completely fine. But when multiple students send message to expert he is not getting all the chats to see. Expert can see the chat of only one student when expert login and click on chat icon => he gets the below page
> > > oneChatOnly
> > > in above imags you can see the student02(and when you click on it you can see chats) but currently I have messaged the same expert as another student also, but name of that student is not displayed here
> > 
> > 
> > it works fine for me
> 
> @jelly-afk As an expert are you receiving chats of more than one student ?

i cant try right now as i dont have the env variables but it was working last time and the code looks correct too

**Comment by samarthhapse** [comment]
@jelly-afk , which env variables you want , I can provide my personal ones

**Comment by jelly-afk** [comment]
> @jelly-afk , which env variables you want , I can provide my personal ones

razor pay

**Comment by samarthhapse** [comment]
@jelly-afk ,

RAZORPAY_KEY_ID='rzp_test_qMlS67mEE4RB9A'
RAZORPAY_SECRET_KEY='hM5mJnEzfXIl3S0uHFOILg1U'

**Pull request merged**
