### PR TITLE
Implement Automated Commenting System for Issue Formatting

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
This pull request adds an automated commenting system to prompt contributors to provide essential details like titles and descriptions when submitting issues. The system aims to improve issue quality and streamline communication by standardizing formatting requirements.

### CODE REVIEW

**Comment by samarthhapse** [comment]
@thevijayshankersharma , I required the feature of automated commenting in my app. You made it for my repo. we got into some misunderstanding. But I can't merge this one.

**Comment by thevijayshankersharma** [comment]
@samarthhapse So you don't need auto comment in your repo ? 
I can add auto greet on issues or PRs, comment on closed issues or PRs etc. If you need it then tell me . I would like to make.

**Comment by samarthhapse** [comment]
no

**Comment by samarthhapse** [comment]
If I need something like this , I will reach out

**Comment by thevijayshankersharma** [comment]
OK.

**Pull request closed without merging**
