### PR TITLE
Created The Whole UI for the website Main Page

### PR DESCRIPTION
**Pull request by Priyanshu2743**
I have added the UI for the Website main page 

Now it looks like -: 

image
image
image

### CODE REVIEW

**Comment by Priyanshu2743** [comment]
I will resolve the conflicts by tomorrow

**Comment by samarthhapse** [comment]
Recently I have merged the code. Fork code now and then add your code, post complete video by signing in and logging in to check if there aren't any error in code. Then I will add labels to your repo.

**Comment by Priyanshu2743** [comment]
Ok

**Comment by samarthhapse** [comment]
did you resolve conflicts ? If not , do by afternoon first make working video and then make PR.

**Comment by Priyanshu2743** [comment]
Ok I'll done it by 6pm

**Comment by samarthhapse** [comment]
hello @Priyanshu2743 why taking so much time . I merged one more PR now. Clone it now and add your code there.

**Comment by samarthhapse** [comment]
then make aa PR by today evening itself

**Comment by samarthhapse** [comment]
Hello @Priyanshu2743 do not make any PR for next 3-4 days. You can take more time to modify UI and match it with reference UI provided by me. Once you are done comment here and then raise the PR. after my confirmation. I will add labels of gssoc and *level3*

**Comment by samarthhapse** [comment]
comment and start building early

**Comment by samarthhapse** [comment]
comment if you have started, or let me assign to anyone else

**Comment by Priyanshu2743** [comment]
I have created 
i will create merge request by today

**Pull request closed without merging**
