### PR TITLE
Add Eye Icon on password and Confirm password input

### PR DESCRIPTION
**Pull request by gaurav1603**
Issue No : #176 
Issue Title : Adding an eye button in the password field
 
Description : Add Eye icon on password and confirm password input field  in both expert and student login and signup form

Screenshot 2024-06-20 162835

### CODE REVIEW

**Comment by samarthhapse** [comment]
@gaurav1603 already this issue was assigned to someone else , but he just completed it for login section. But as I assigned i to him , I have merged his PR. But your his PR can do it for login as well as signup , but now there are some conflicts bcs of previous PR . Pls resolve the conflicts and raise PR again.

**Comment by gaurav1603** [comment]
please check once again

**Comment by samarthhapse** [comment]
@gaurav1603 can you pls raise this PR on temp4 branch

**Comment by samarthhapse** [comment]
there are some other issues with current temp branch

**Comment by gaurav1603** [comment]
please check again

**Comment by samarthhapse** [comment]
@gaurav1603 pls raise PR on current temp branch now.

**Pull request closed without merging**
