### PR TITLE
Feat/authorizization updated

### PR DESCRIPTION
**Pull request by AADESHak007**
Updated the email response upon successful confirmation of the code

### CODE REVIEW

**Comment by samarthhapse** [comment]
@AADESHak007 checked it again, I do not get any reply when I click on submit button after entering otp

**Comment by samarthhapse** [comment]
@AADESHak007 , try to run on your side first ensure it is working properly and then raise PR

**Comment by AADESHak007** [comment]
I am checking the issue once again in the meantime why don't you connect with me on DISCORD .
username :  aadeshak007

**Comment by samarthhapse** [comment]
@AADESHak007 why not , sent a request

**Pull request merged**
