### PR TITLE
build frontend authorization section according to backend requirements

### PR DESCRIPTION
**Pull request by AbhiDiva96**
## Related issue

 Fixes : #10 

## Home page
Screenshot 2024-05-26 081345

## Student Home page
Screenshot 2024-05-26 081352

## Student signup login and resetPassword page

Screenshot 2024-05-26 082639
Screenshot 2024-05-26 081442
Screenshot 2024-05-26 081450

## Expert Home page
Screenshot 2024-05-26 081510

## Expert singUp signIn and reset page

Screenshot 2024-05-26 081520
Screenshot 2024-05-26 081528

## Database image
Screenshot 2024-05-26 083708

## student DB
Screenshot 2024-05-26 083719

## Expert DB
Screenshot 2024-05-26 083726

### CODE REVIEW

**Comment by samarthhapse** [comment]
as you have mentioned in the note that there are a lots of changes remaining. Comment here, if you are willing to work on it.

**Comment by AbhiDiva96** [comment]
yeah sure. @samarthhapse 
 I am willing to work on this project.

**Comment by samarthhapse** [comment]
Hello @AbhiDiva96  , available to work on #215 OR #216

**Comment by AbhiDiva96** [comment]
Ya I am happy to work on the issue one by one @samarthhapse 
Pls assign me accordingly

**Pull request merged**
