### PR TITLE
Fix/otpverifyexpert path

### LINKED ISSUE #155: fixing backend of verifyotp route for (expert signup)
try to signup as an expert and student as well. Just if able to register and signin for both (student) and (expert) things , @jelly-afk you can raise PR

### PR DESCRIPTION
**Pull request by jelly-afk**
fixes #155 added otpverifyexpert route

### CODE REVIEW

**Comment by samarthhapse** [comment]
well done @jelly-afk , it's done. I have added gssoc lables and levels to all your PRs and issues. Which will help you get hike on leaderboard.

As it seems like you got better understanding of backend of this app , If you want to work on #90 you can comment there. I will assign it.

**Comment by jelly-afk** [comment]
thanks @samarthhapse , but i am not in gsoc , i just found this repo on github explore, can i still contribute?

**Comment by samarthhapse** [comment]
No problem , you can still contribute here

**Comment by samarthhapse** [comment]
just share your mail id here

**Comment by jelly-afk** [comment]
jellybeans33124@gmail.com

**Pull request merged**
