### PR TITLE
added preloader 

### PR DESCRIPTION
**Pull request by Jagpreet153**
Added a responsive preloader of dark theme

Solves : #69 

Screenshot 2024-05-27 235236

Kindly add GSSoC'24 tag to the PR

### CODE REVIEW

**Comment by samarthhapse** [comment]
@Jagpreet153  you have replaced the app component with preloader, pls share the working video to check isn't there any issue in previous code. Signup and login with dummy data.

**Comment by Jagpreet153** [comment]
> @Jagpreet153 you have replaced the app component with preloader, pls share the working video to check isn't there any issue in previous code. Signup and login with dummy data.

NO, @samarthhapse It won't affect the App component as 
1. The app components now renders within preloader components and only when the page is totally loaded . 
2. It won't affect the backend code as the preloader component deals with frontend  

I have signed up a expert however could'nt login because it shows internal server error.

https://github.com/samarthhapse/sarthi/assets/119691733/64267687-944b-47a6-9154-e9815fb35d5b

**Comment by samarthhapse** [comment]
Yeah ! I checked it , and also added labels to PR

**Comment by Jagpreet153** [comment]
@samarthhapse Kindly add me as assignee to this PR else points won't be calculated in GSSoC'24

**Comment by samarthhapse** [comment]
done

**Pull request merged**
