### PR TITLE
Chat functionality backend

### PR DESCRIPTION
**Pull request by mehtakevan**
I have implemented the backend for chat functionality. Resolved the issue #11.

### CODE REVIEW

**Comment by samarthhapse** [comment]
@mehtakevan , it is expected to just create a very simple page in frontend to ensure the functionality is working and further contributor to understand how to enhance this thing. I request to build a very simple (basic) page showing the functionality of the page in frontend.

**Comment by samarthhapse** [comment]
@mehtakevan , I am opening new issue for this basic chat UI page

**Comment by samarthhapse** [comment]
@mehtakevan , pls comment on #182. I will assign it.

**Comment by samarthhapse** [comment]
@mehtakevan , there are so much errors in code. Haven't you tied it out. Please resolve them and also add frontend

**Comment by mehtakevan** [comment]
@samarthhapse it is working fine on my system. I have checked it and then created a PR. Then also just brief me what is the exact error that you are encountering.

**Comment by samarthhapse** [comment]
Screenshot 2024-06-22 092211

**Comment by samarthhapse** [comment]
@mehtakevan I tried to do some changes , but getting more errors continuously

**Comment by mehtakevan** [comment]
@samarthhapse okay, let me check it. I will get back to you. This is weird error that module is not found though it is there in that path mentioned.

**Comment by samarthhapse** [comment]
@mehtakevan , yes please change and add nominal frontend part, just to understand functioning before raising PR

**Comment by mehtakevan** [comment]
@samarthhapse  Okay sure. 
Do you have any idea that why this kind of error is raising. Because as we know that the module is there in the mentioned path but node is not able to recognize it?

**Comment by mehtakevan** [comment]
@samarthhapse as I again cloned the repository to check that this error persist in my system or not? And I have got the same error. But when I raised the PR it was working fine on my system. The internal code has no mistakes but the node is not able to find the modules only.

**Comment by samarthhapse** [comment]
pls try to for the code from temp4 branch. I merged your code and then created the temp 4 branch

**Comment by samarthhapse** [comment]
all the changes made from your side only are updated in temp4. Pls see is it working

**Comment by mehtakevan** [comment]
@samarthhapse Do not worry. Solved that module not found error from temp branch too. Now I will raise a PR with frontend only. I have some frontend designed for chat application.

**Comment by samarthhapse** [comment]
Okay @mehtakevan , but hoe you solved this

**Comment by mehtakevan** [comment]
@samarthhapse I don't know why but if I was not providing the file extension(.js) in import statement than node was not able to find that file. I just added the file extension in the import statement file path.

Like this::
image

**Comment by samarthhapse** [comment]
When student sign in and then selects the expert , then you will get one blank page , here you have to add the chat button (and a basic design of chat page on click of this chat button)

**Comment by mehtakevan** [comment]
@samarthhapse otherwise normally we don't provide the file extension in import.

**Comment by samarthhapse** [comment]
> @samarthhapse otherwise normally we don't provide the file extension in import. 

Okay

**Comment by samarthhapse** [comment]
hello @mehtakevan , can you please fork the code from temp4 branch only and then start working

**Comment by samarthhapse** [comment]
pls do not get code from temp branch , I think there might be some issues regarding other functionalities

**Comment by samarthhapse** [comment]
@mehtakevan noted ? to get code from temp 4 branch. I have also set temp4 branch as default

**Comment by mehtakevan** [comment]
@mehtakevan okay done. Noted

**Comment by samarthhapse** [comment]
well !

**Comment by mehtakevan** [comment]
@samarthhapse When I was trying to run the client part, I found one issue in studentsignup. There were some missing closing brackets and the default export was not written. Check that once

**Comment by samarthhapse** [comment]
I think that is bcs of code from temp branch.  Once just try with temp4

**Comment by samarthhapse** [comment]
Bcs. Till the temp4 is branch which has only : your code of backend + previous working code

**Comment by mehtakevan** [comment]
@samarthhapse okay noted.

**Comment by mehtakevan** [comment]
@samarthhapse I have completed with the backend task. But to design a simple frontend also will take much time. So can I just create a PR for backend? I have made all the necessary comments in backend so whosoever will look at it will definitely understand it.

**Comment by samarthhapse** [comment]
okay , If it is running completely fine (both client & server) , pls raise PR

**Comment by samarthhapse** [comment]
@mehtakevan , but if you can create UI , pls take 2-3 days , but my opinion is only you should create it. After all decision is yours.

**Comment by mehtakevan** [comment]
@samarthhapse I would also have loved to contribute in UI. But I can't commit anything for next week so I don't want to give false hopes or false commitment. I will definitely try to implement it and if I will able to do that then I will raise an issue for the same but currently I am not committing anything. I haved raised a PR for backend, check that once. It was very nice to work with you!!

**Comment by samarthhapse** [comment]
Okay @mehtakevan , well done with backend part.

**Comment by mehtakevan** [comment]
@samarthhapse Thanks!!!!

**Comment by mehtakevan** [comment]
@samarthhapse please make me as assignee

**Pull request merged**
