### PR TITLE
Added eye in pw field in student & expert login

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #176 

https://github.com/samarthhapse/sarthi/assets/154724111/72c477e9-376a-4d7b-a1d4-e971211bbebd

### CODE REVIEW

**Comment by pani2004** [comment]
@samarthhapse Pls review this PR!!!

**Comment by samarthhapse** [comment]
@pani2004 well done with issue . Adding the labels

**Comment by pani2004** [comment]
@samarthhapse Will the level3 tag count in the points now? as this PR has already been counted in the leaderboard

**Comment by samarthhapse** [comment]
Hello @pani2004  , available to work on #215 OR #216

**Pull request merged**
